baseurl             = "https://akhilpandey95.com/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Akhil Pandey"
title               = "Akhil Pandey"
pygmentsuseclasses  = true
# disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-135077366-1"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "About"
weight                 = 100
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Projects"
weight                 = 3
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "Blog"
weight                 = 2
identifier             = "blog"
url                    = "/blog/"

[params]
include_rss            = false                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Akhil Pandey"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "akhilpandey95@icloud.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
github                 = "https://github.com/akhilpandey95"
# if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik


avatar                 = "img/me.jpeg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
